version: '3.8'

services:
  node1:
    build: .
    ports:
      - "5000:5000"
    networks:
      - blockchain_network

  node2:
    build: .
    ports:
      - "5001:5000"
    networks:
      - blockchain_network

networks:
  blockchain_network:
